// <auto-generated />
namespace VotingApplication.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HiddenResults_To_RevotingDisabled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HiddenResults_To_RevotingDisabled));
        
        string IMigrationMetadata.Id
        {
            get { return "201506020829192_HiddenResults_To_RevotingDisabled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
